apiVersion: apps/v1
kind: Deployment
metadata:
  name: Medicure_App
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Medicure_App
  template:
    metadata:
      labels:
        app: Medicure_App

      containers:
      - name: Medicure_App
        image: jharajltp/java-app:latest
        ports:
        - containerPort: 8082
